# Generated by Django 5.2.1 on 2025-05-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
